### ISSUE TITLE
Anomaly under GPD

### ISSUE THREAD

**Issue by kashif** [robjhyndman/weird#1]
In the line where we check if the new `$y_{i,t+1}$ as an anomaly` do we need to do something to ensure that the score `s_{i,t+1}` is not less than the `loc` parameter of the GPD?

https://github.com/robjhyndman/weird/blob/f1ced3540266b1c3b5f63292a9b865859c100ddb/09-timeseries.qmd#L496

thanks for any insights!

**Comment by robjhyndman** [comment]
No. The probability will be 1 in that case.

**Comment by kashif** [comment]
BTW the same technique also works with neural probablistic forecasters: https://github.com/kashif/gluon-ts/blob/gp-distribution/examples/anomaly_detection_pytorch.py#L174-L178
